version: '3'
services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_DB: $DB_NAME
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USERNAME -d $DB_NAME"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    image: scraping
    build:
      context: ./scraping
    volumes:
      - "./scraping:/code"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: $DB_NAME
      DB_PASSWORD: $DB_PASSWORD
      DB_USERNAME: $DB_USERNAME
    depends_on:
      database:
        condition: service_healthy
  api:
    image: api_endpoint
    build:
      context: ./api
    volumes:
      - "./api:/code"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: $DB_NAME
      DB_PASSWORD: $DB_PASSWORD
      DB_USERNAME: $DB_USERNAME
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy

  
      
    