swagger: "2.0"
info:
  title: API
  description: API description in Markdown.
  version: 1.0.0
host: 0.0.0.0:8000
basePath: /parts
schemes:
  - http
paths:
  /parts:
    get:
      summary: Gets a parts data for a particular manufacturer, category and model
      parameters:
        - in: query
          name: manufacturer
          type: string
          required: true
        - in: query
          name: category
          type: string
          required: true
        - in: query
          name: model
          type: string
          required: true
      responses:
        200:
          description: OK
        422:
          description: A query parameter missing / Unprocessable Entity
        500:
          description: Internal Server Error
    